### ISSUE TITLE
vigra update 1.11.2 blocked

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#2776]
As much as we'd like to update `vigra` to 1.11.2 (no more pinning on specific build ...) it's currently blocked: On linux, our environment will fail to solve due to an older version of `libjpeg-turbo` on the pytorch channel shadowing the one on conda-forge (which would be required for `vigra`). There are options of course:

1. Don't insist on having the same environment file on all operating systems. Major downside I see here, that also the installation instructions for our `ilastik` conda package would have to be adapted.
2. Don't source `pytorch` from the pytorch channel: not an option on Windows. Also with cuda 
3. Use [channel specifiers](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) in the environment file to force `libjpeg-turbo` from conda-forge: Doesn't work:
    ```yaml
    channels:
      - pytorch
      - conda-forge

    dependencies:
      - python 3.9.*
      - pytorch
      - vigra 1.11.2.*
      - conda-forge::libjpeg-turbo
    ```
4.  Don't use [strict channel priority](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html?highlight=strict%20channel#strict-channel-priority) - this way it would be possible for packages from lower priority channels to override higher priority ones in case of newer versions. This would mean possibly longer solving times, and also less reliable results.

I'll try to find out why channel specifiers don't work, first - as this would be for now the easiest solution.
